name: Directories and Repo Info

on: 
  workflow_dispatch:

jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List top-level directories
        run: |
          echo "Listing directories in repo root:"
          ls -d */

      - name: Echo GitHub repo name using variable
        run: echo "This workflow is running for repo: ${{ github.repository }}"
