name: tester
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-repo
        uses: actions/checkout@v4

      - name: get all folder name
        run: |
          ls
          echo "woring?"
          list=$(ls)
          echo  "the directories are" 
          for i in $list;
          do 
            echo "$i"
          done
          
      - name: Store README section
        run: |
          {
            echo "README_SECTION<<EOF"
            echo "### 📌 Placement Questions"
            echo
            echo "- Read the [\`contributing.md\`](./contributing.md) to learn how you can expand our community."
            echo "- Explore the collection of valuable questions and information to help you get placed in your dream company."
            echo 
            echo "### COMPANIES"
            echo "EOF"
          } >> $GITHUB_ENV


          

      - name: retrieve and check
        run: |
          echo "$README_SECTION"

      - name: Create placement.md file
        run: |
          echo "$README_SECTION" > placement.md

      - name: Commit placement.md to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add placement.md
          git commit -m "Add placement.md from workflow"
          git push

