name: tester
on:
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-repo
        uses: actions/checkout@v4

      - name: get all folder name
        run: |
          ls
          echo "woring?"
